name: Webhook Trigger

on:
  repository_dispatch:
    types: [webhook]

jobs:
  print-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Webhook Payload
        run: |
          echo "Webhook payload: ${{ github.event.inputs.payload }}"
